name: google_signin
description: A new Flutter project.
publish_to: 'none'
version: 1.1.1+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_messaging: ^14.7.10
  google_sign_in: ^6.1.6
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  barcode_scan2: ^4.5.1
  http: ^1.2.2
  permission_handler: ^12.0.0+1
  flutter_expandable_fab: ^2.0.0
  cloud_firestore: ^4.13.6
  flutter_launcher_icons: ^0.13.1
  flutter_colorpicker: ^1.1.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.0.7
  firebase_storage: ^11.5.6
  intl: ^0.19.0
  share_plus: ^7.2.1
  app_links: ^3.4.1
  firebase_dynamic_links: ^5.4.8
  url_launcher: ^6.2.4
  flutter_svg: ^2.0.9
  flutter_local_notifications: ^19.2.0
  package_info_plus: ^8.3.0
  path_provider: ^2.1.1
  dio: ^5.4.0
  open_file: ^3.3.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/logos/